# Generated by Django 4.1.5 on 2023-01-30 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('birthday_date', models.DateField()),
                ('genre', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('2', 'Otro')], default='0', max_length=10)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2023, 1, 29, 20, 58, 6, 879468))),
            ],
        ),
    ]
